/* tslint:disable */
/* eslint-disable */
/**
 * Stable - Auth Service
 * An authentication service API for Stable
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface LoginUserRequestDto
 */
export interface LoginUserRequestDto {
    /**
     * The email of the user
     * @type {string}
     * @memberof LoginUserRequestDto
     */
    'email': string;
    /**
     * The password of the user (minimum 8 characters)
     * @type {string}
     * @memberof LoginUserRequestDto
     */
    'password': string;
    /**
     * The new password to set for the user (optional, minimum 8 characters)
     * @type {string}
     * @memberof LoginUserRequestDto
     */
    'newPassword'?: string;
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Log in a user
         * @param {LoginUserRequestDto} loginUserRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginControllerLogin: async (loginUserRequestDto: LoginUserRequestDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginUserRequestDto' is not null or undefined
            assertParamExists('authLoginControllerLogin', 'loginUserRequestDto', loginUserRequestDto)
            const localVarPath = `/auth/users/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginUserRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Log in a user
         * @param {LoginUserRequestDto} loginUserRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLoginControllerLogin(loginUserRequestDto: LoginUserRequestDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLoginControllerLogin(loginUserRequestDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @summary Log in a user
         * @param {LoginUserRequestDto} loginUserRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginControllerLogin(loginUserRequestDto: LoginUserRequestDto, options?: any): AxiosPromise<void> {
            return localVarFp.authLoginControllerLogin(loginUserRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @summary Log in a user
     * @param {LoginUserRequestDto} loginUserRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authLoginControllerLogin(loginUserRequestDto: LoginUserRequestDto, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).authLoginControllerLogin(loginUserRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}


